In [1]:
import pandas as pd
import numpy as np

#import from the base.csv from this directory   header is 1st row, index is 1st column

df = pd.read_csv('base.csv' , header=1, index_col=0)

In [16]:
#import data from csv
df = pd.read_csv('base.csv' , header=1, index_col=0)
#import from shoot.csv
df_shoot = pd.read_csv('shooting.csv' , header=1, index_col=0)
#import from pass.csv
df_pass = pd.read_csv('passing.csv' , header=1, index_col=0)
#import from goal_creation.csv
df_goal_creation = pd.read_csv('goal_creation.csv' , header=1, index_col=0)
#import from defence.csv
df_defence = pd.read_csv('defensive.csv' , header=1, index_col=0)
#import from possession.csv
df_possession = pd.read_csv('possession.csv' , header=1, index_col=0)

#merge all into df dataframe using name as index
# Merge all DataFrames on 'Player'
df = pd.merge(df, df_shoot, on='Player', suffixes=('', '_shoot'))
df = pd.merge(df, df_pass, on='Player', suffixes=('', '_pass'))
df = pd.merge(df, df_goal_creation, on='Player', suffixes=('', '_goal_creation'))
df = pd.merge(df, df_defence, on='Player', suffixes=('', '_defence'))
df = pd.merge(df, df_possession, on='Player', suffixes=('', '_possession'))
# Remove duplicate columns by keeping only the original ones
columns_to_keep = []
for column in df.columns:
    if column.endswith(('_shoot', '_pass', '_goal_creation', '_defence', '_possession')):
        original_column = column.rsplit('_', 1)[0]
        if original_column not in df.columns:
            df.rename(columns={column: original_column}, inplace=True)
    else:
        columns_to_keep.append(column)

df = df[columns_to_keep]
df['Age'] = df['Age'].str[:2]
#create a new column with the age as an int
df['Age'] = df['Age'].astype(int)
#make nation only the last 3  letters of the nation column
df['Nation'] = df['Nation'].str[-3:]
#make the nation column a string
df['Nation'] = df['Nation'].astype(str)

In [23]:
df.head(5)

,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,...,Live,Succ,Succ%,Tkld,Tkld%,Carries,CPA,Mis,Dis,Rec
0,Brenden Aaronson,USA,MFFW,Leeds United,22,2000,32,28,2296,25.5,...,1105,34,34.0,48,48.0,666,13,69,79,746
1,Che Adams,SCO,FW,Southampton,26,1996,25,22,1873,20.8,...,681,15,50.0,11,36.7,382,9,65,24,529
2,Tyler Adams,USA,MF,Leeds United,24,1999,24,24,2156,24.0,...,1628,7,31.8,12,54.5,818,0,28,18,919
3,Tosin Adarabioyo,ENG,DF,Fulham,25,1997,19,17,1545,17.2,...,1122,4,66.7,2,33.3,596,1,2,4,686
4,Nayef Aguerd,MAR,DF,West Ham,27,1996,14,13,1235,13.7,...,710,4,66.7,0,0.0,409,0,8,4,439

In [21]:
df = df.drop_duplicates(subset=['Player'], keep='first')

In [4]:
def ascii_table(data):
    # Split data into rows
    rows = data.strip().split('\n')

    # Extract header and data
    header = rows[0].split()
    data = [row.split() for row in rows[1:]]

    # Determine column widths
    col_widths = [max(len(row[i]) for row in data) for i in range(len(header))]

    # Build table
    table = ''
    table += '+'.join(['-'*(w+2) for w in col_widths]) + '+\n'
    table += '| ' + ' | '.join(header[i].ljust(col_widths[i]) for i in range(len(header))) + ' |\n'
    table += '+'.join(['-'*(w+2) for w in col_widths]) + '+\n'
    for row in data:
        table += '| ' + ' | '.join(row[i].ljust(col_widths[i]) for i in range(len(header))) + ' |\n'
    table += '+'.join(['-'*(w+2) for w in col_widths]) + '+'

    return table

In [9]:


text = """a dataframe with 20 columns about soccer has an example row  as such 
Rk,Player,Nation,Pos,Squad,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,xG,npxG,xAG,npxG+xAG,PrgC,PrgP,PrgR,Gls,Ast,G+A,G-PK,G+A-PK,xG,xAG,xG+xAG,npxG,npxG+xAG,Matches,-9999
1,Brenden Aaronson,us USA,MFFW,Leeds United,22-187,2000,32,28,2296,25.5,1,3,4,1,0,0,2,0,3.7,3.7,4.2,7.9,43,84,147,0.04,0.12,0.16,0.04,0.16,0.14,0.17,0.31,0.14,0.31,Matches,5bc43860
 the rows are explained Rk: Rank from top to bottom

 when manchester united is searched the is filtered for Manchester Utd in Squad
 Nott'ham Forest is nottingham forest try to make adjustments for these 
 sometimes tottenham is called spurs and Manchester Utd red devils
Nation: Nationality
Pos: Position played
Age: Current age
Born: Year of birth
MP: Matches played
Starts: Games started
Min: Minutes played
90s: Minutes played divided by 90
Gls: Goals scored
Ast: Assists
G+A: Goals + Assists
G-PK: Non-penalty goals
PK: Penalty kicks made
PKatt: Penalty kicks attempted
CrdY: Yellow cards
CrdR: Red cards
xG: Expected goals
npxG: Non-penalty expected goals
xAG: Expected assisted goals
npxG+xAG: Non-penalty expected goals plus assisted goals
PrgC: Progressive carries
PrgP: Progressive passes
PrgR: Progressive passes received
Goals/90: Goals scored per 90 minutes
Assists/90: Assists per 90 minutes
G+A/90: Goals and assists per 90 minutes
Non-penalty goals/90: Non-penalty goals scored per 90 minutes
Non-penalty G+A/90: Non-penalty goals and assists per 90 minutes
xG/90: Expected goals per 90 minutes
xAG/90: Expected assisted goals per 90 minutes
xG+xAG/90: Expected goals plus assisted goals per 90 minutes
npxG/90: Non-penalty expected goals per 90 minutes
npxG+xAG/90: Non-penalty expected goals plus assisted goals per 90 minutes


Q: Top 5 most goals scored by a defender under 21?\n"
df_defenders_under_21 = df[(df['Pos'] == 'DF') & (df['Age'] < 21)]\n
df_defenders_under_21 = df_defenders_under_21[['Player', 'Squad', 'Pos', 'Age', 'Gls', 'MP']]\n
df_defenders_under_21.sort_values(by='Gls', ascending=False, inplace=True)\n
print(df_defenders_under_21.head(5).to_html(index=False))\n

Q: Top 5 most goals scored by an English midfielder under 21 ?\n
df_midfielders_under_21 = df[(df['Pos'] == 'MF') & (df['Age'] < 21) & (df['Nation'] == 'eng ENG')]\n
df_midfielders_under_21 = df_midfielders_under_21[['Player', 'Squad', 'Pos', 'Age', 'Gls', 'MP']]\n
df_midfielders_under_21.sort_values(by='Gls', ascending=False, inplace=True)\n
print(df_midfielders_under_21.head(5).to_html(index=False))\n

Q: Who is the oldest player with an assist\n
df_assist = df[df['Ast'] > 0]\n
df_assist = df_assist[['Player', 'Squad', 'Pos', 'Age', 'Ast', 'MP']]\n
df_assist.sort_values(by='Age', ascending=False, inplace=True)\n
print(df_assist.head(1).to_html(index=False))\n
Q: Who is the top assister amongst these 3 teams, Brighton, Brentford, and Crystal Palace\n
df_teams = df[(df['Squad'] == 'Brighton') | (df['Squad'] == 'Brentford') | (df['Squad'] == 'Crystal Palace')]\n
df_teams = df_teams[['Player', 'Squad', 'Pos', 'Age', 'Ast', 'MP']]\n
df_teams.sort_values(by='Ast', ascending=False, inplace=True)\n
print(df_teams.head(1).to_html(index=False))\n
Q: players with most goals from manchester united\n
df_players =df['Squad'] == 'Manchester Utd')\n
df_players.sort_values(by='Gls', ascending=False, inplace=True)\n
print(df_players.head(1).to_html(index=False))\n


Q:"""




from tiktoken import Tokenizer
from tiktoken import Tokenizer as TikTokenizer



# Initialize tokenizer
tokenizer = TikTokenizer()

# Count tokens
token_count = len(list(tokenizer.tokenize(text)))

print(f"Token count: {token_count}")

ImportError: cannot import name 'Tokenizer' from 'tiktoken' (C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\__init__.py)